theme: jekyll-theme-minimal
title: Gedeon Muhawenayo
description: Graduate Student
url: https://gedeonmuhawenayo.github.io/
github_username:  gedeonmuhawenayo
google_analytics: UA-131476591-1
logo: https://avatars.githubusercontent.com/u/50500636?v=4
show_downloads: false
